### ISSUE TITLE
Wrapped menus do not differentiate between normal and mirror eggs

### ISSUE THREAD

**Issue by baptistemarchand** [olriko/captain-crepe#2]

**Comment by baptistemarchand** [comment]
This is fixed now that the two eggs are different ingredients

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
wuzhuzhu, @j05u3, @martin-spa, @VlodkoMr, @PascalDierich, @GustavoRSSilva, @skomg, @jessynt, @danigorbaciov, @visualrobots, @yannamsellem, @SweetieRick, @EDDIE2-max, @nanyang24, @ferrallas, @gustavomts, @Planxnx, @gmingshanao, @griffinmartin, @SarahKay99, @Suzan-Dev, @nikitavasilev, @pragkent, @bigdragon1977, @ErwinRussel, @sshmaxime, @v4lproik, @mhaidarhanif, @peytonbgregory, @soyccan, @maxoumime, @charbelrami, @paolodapul, @foolstack-omg, @HappyUniversity, @POPPIN-FUMI, @blackestwhite, @Yepman0620, @JingwenTian, @vloddos, @giuliocorradini, @alexkubica, @Surajv311, @taerbao, @gopherxin, @tlands, @GanB, @fahmidme, @helderavila, @ZojusaneKavyakodanda, @yasaricli, @ricardohead, @yakushevhk, @madeye, @ryunika, @Amirbarzegari, @thanit456, @carllippert, @deevolutionism, @albertofem, @skill-issue0, @luckytiger1, @didoshotev, @mikeboiko, @swak, @SSaratKS, @EngEryx, @boy520520456, @GuoTianqi, @masaun, @iamvon, @spstar, @ilmoi, @zyp001a, @akizor, @DhruvDave12, @radiovan18, @amancioandre, @adryan30, @jaxrtech, @SumonMSelim, @yuis-ice, @Durantdzr, @Devorein, @khaled, @RicardoLSantos, @mulfdev, @jspw, @moreal, @norainc, @dafang, @thatalexay, @Jonathan-Nucleus, @Apoll95, @zhangyouxin, @SuSuSoo, @greyireland, @playflycode, @erdemdemirkapidaevid, @JIVIN0902, @ArshaanB, @dennissu77, @klasdfji, @alanhc, @damphat, @GVRV, @josephedward, @wairimumiringu6, @Sakiya999, @subin-j, @deepakchandola786, @boybundit, @Petsonal, @aerophobic, @D3Portillo, @Vinnyvader, @sinaebrahimi, @ketoin, @phuhao00, @struggledhard, @barisates, @zhaoyang110157, @X-oss-byte, @adryan30, @rhinoxi, @butterfly0503, @msemenistyi, @data-miner00, @shibu885, @pradeepmisra81, @emberfarkas, @jyeray, @Alexader, @Vienio99, @Jimmerz28, @bozzmob, @amirgamil, @Sultan099, @officialvlad69, @BDollie, @s7v7nislands, @xeusteerapat, @Quantum2Hybridization, @D3strukt0r, @QuangToo, @abhilov23, @Newmaker0, @tonyjunkes
